### ISSUE TITLE
How to manually compile YGO Pro from the Source Code?

### ISSUE THREAD

**Issue by azispratama92** [cromerc/ygopro#2]
Hello sir, I am a newbie GNU/Linux user. Knowing that some good people creating a native YGO Pro for UNIX OSes (Mac and Linux) is really makes me happy :)

I'm wondering tho, how do we compile (create a binary launcher from the source code of the YGO Pro). 

All i know is, the code is written in C++ language, so is it possible to compile it under Qt Creator, to make a binary launcher? 

Many thanks ^ ^

**Comment by cromerc** [comment]
You can compile the code with this command:
    premake4 gmake && make -Cbuild
